// Global using directives

global using System.Text;
global using System.Text.Json;
global using DevSync.PocPro.Shared.Domain.Events;
global using DevSync.PocPro.Shared.Domain.Utils;
global using DevSync.PocPro.Shops.Api.Data;
global using DevSync.PocPro.Shops.Api.EventHandlers;
global using DevSync.PocPro.Shops.Api.Services;
global using DevSync.PocPro.Shops.Api.Utils;
global using DevSync.PocPro.Shops.GeneralSettings.Data;
global using DevSync.PocPro.Shops.GeneralSettings.Domain;
global using DevSync.PocPro.Shops.OrdersModule.Data;
global using DevSync.PocPro.Shops.OrdersModule.Domain;
global using DevSync.PocPro.Shops.PointOfSales.Data;
global using DevSync.PocPro.Shops.PointOfSales.Domains;
global using DevSync.PocPro.Shops.PrivateCustomers.Data;
global using DevSync.PocPro.Shops.PrivateCustomers.Domain;
global using DevSync.PocPro.Shops.Shared.Services;
global using DevSync.PocPro.Shops.StocksModule.Data;
global using DevSync.PocPro.Shops.StocksModule.DI;
global using DevSync.PocPro.Shops.StocksModule.Domains;
global using DevSync.PocPro.Shops.UserWishlistModule.Data;
global using DevSync.PocPro.Shops.UserWishlistModule.Domains;
global using FastEndpoints;
global using Marten;
global using Microsoft.EntityFrameworkCore;
global using RabbitMQ.Client;
global using RabbitMQ.Client.Events;
global using Scalar.AspNetCore;
global using Order = DevSync.PocPro.Shops.OrdersModule.Domain.Order;