<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DevSync.PocPro.WorkerService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\shops\shared\DevSync.PocPro.Shops.Shared\DevSync.PocPro.Shops.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Events\" />
    </ItemGroup>

</Project>
