// <auto-generated />
using System;
using DevSync.PocPro.Accounts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevSync.PocPro.Accounts.Api.Data.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    partial class AccountsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserPermission", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.HasKey("ApplicationUserId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("ApplicationUserPermission");
                });

            modelBuilder.Entity("DevSync.PocPro.Accounts.Api.Features.ApplicationUsers.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("DevSync.PocPro.Accounts.Api.Features.ApplicationUsers.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198adc5-0ec0-7697-9123-ec6f41fa3993"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 504, DateTimeKind.Unspecified).AddTicks(6530), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_PERMISSIONS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7aea-84a4-06c7c582ec20"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1930), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_USERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7e8f-9f01-95760b3629e4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1940), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_USERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7dec-b627-66d19a3d096d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1950), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_TENANTS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-72ac-9d2b-feeecce53a1e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1960), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_TENANTS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-78ae-b1ce-feb136996f1a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1970), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_PRODUCTS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-709f-bc16-6ea9663cf024"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1970), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_PRODUCTS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-745c-aaa3-a18cc0b660c1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1980), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_CATEGORIES",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7e3d-ad95-cbb06d3363c9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1990), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_SUPPLIERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7507-9f4c-f49535d5eded"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(1990), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_SUPPLIERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-755e-8cad-34792b3b875b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2000), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_STOCKS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7436-b0e6-a0a29801d7e7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2010), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_POS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-797f-bb30-b007dd24c15e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2010), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "GET_POS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7ed9-8951-ceb35f322d5d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2020), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_SALES",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7835-805e-3f85acf10011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2030), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_SALES",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-79c7-b170-3f8d112b8059"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2040), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_PURCHASES",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7688-a9d2-822edbb6c1b2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2040), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_PURCHASES",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7293-94c0-d20e458846f1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2050), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_CUSTOMERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-77f3-8eda-099831000ff4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2060), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_CUSTOMERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7b60-98da-de3d761552c1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2060), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_ORDERS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-769c-a562-aed0ab245436"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2070), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_SESSIONS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7633-bd25-8dfc45aa5ce1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2080), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_BRANDS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-750c-b77c-91cf0ef21bcd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2080), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "VIEW_REPORTS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-71fd-b39c-326e15bdcb72"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2090), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_SETTINGS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-7fb0-be60-bd58ef9ed984"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2100), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_PROMO_CODES",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0198adc5-0ec6-723c-82db-518df87a760d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 15, 15, 47, 9, 510, DateTimeKind.Unspecified).AddTicks(2100), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System",
                            PermissionType = "MANAGE_SUBACCOUNTS",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("DevSync.PocPro.Accounts.Api.Features.Tenants.Domain.SubAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<float>("PercentageCharge")
                        .HasColumnType("real");

                    b.Property<string>("SettlementBank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("SubAccounts");
                });

            modelBuilder.Entity("DevSync.PocPro.Accounts.Api.Features.Tenants.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionType")
                        .HasColumnType("text");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ApplicationUserPermission", b =>
                {
                    b.HasOne("DevSync.PocPro.Accounts.Api.Features.ApplicationUsers.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSync.PocPro.Accounts.Api.Features.ApplicationUsers.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevSync.PocPro.Accounts.Api.Features.Tenants.Domain.SubAccount", b =>
                {
                    b.HasOne("DevSync.PocPro.Accounts.Api.Features.Tenants.Domain.Tenant", null)
                        .WithOne("SubAccount")
                        .HasForeignKey("DevSync.PocPro.Accounts.Api.Features.Tenants.Domain.SubAccount", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevSync.PocPro.Accounts.Api.Features.Tenants.Domain.Tenant", b =>
                {
                    b.Navigation("SubAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
